- Makefile
- js/Makefile
The shell built-in `command` used in Makefiles would sometimes not work,
yielding the error `command: Command not found`. This was due to an
optimization that make does: For simple commands, make may avoid
spawning a new shell. `command`, being a built-in shell command, would
then not be found.
The program `which` does not suffer from this problem.
> fix: instead of using `command` use `which` in Makefiles

- jupyter-client.el
I added a custom variable to allow usage of tooltips instead of `message` for short messages.
For longer return values the output is still forwarded to a buffer.
I implemented it with a customizable variable `jupyter-display-output-function` that is a symbol (either `'message` or `'tooltip`) which is then checked in a `cond` to ensure that only those two cases are used and no arbitrary function can be added.
I hope my code somewhat matches the style of this package
> Add variable to change output to tooltip instead of message

- README.org
- jupyter-org-client.el
- test/jupyter-test.el
A BEGIN_SRC block can specify which mime type to display by enabling the
user to manually set the priority order of mime types.
e.g.:
In the following, :text/plain will be used before considering :text/html
\#BEGIN_SRC jupy-python :display plain html
> feature: Specify mime precedence using ":display" in org source blocks

- jupyter-mime.el
- jupyter-org-client.el
- ob-jupyter.el
- test/jupyter-test.el
This pull request causes ANSI escape sequences in `org-mode` example blocks or fixed-width (lines that start with `: `) elements to be colored and the actual escape sequences are rendered invisible.
There are issues with this though, since now the escape sequences exist in the buffer instead of being removed before insertion. This means that when exporting to other formats those escape sequences will still be in the exported output.
One way to address this is to hook into `org-mode`'s export functionality and remove the escape sequences in the `example-block` and `fixed-width` elements that `org-mode` processes during export. This should only be done for `example-block` and `fixed-width` elements that are part of the results of Jupyter source blocks since there may be situations where …
> Handle ANSI escape sequences in `org-mode` src-block results

- jupyter-org-extensions.el
- ob-jupyter.el
- test/jupyter-test.el
In the current version of `jupyter-org-execute-to-point`, all source blocks before point are executed indiscriminately of the `:session` header argument or whether the source block is a Jupyter source block. This is not much of an issue if one uses a single session per `org-mode` file, but becomes a problem when multiple sessions exist in various subtrees before point and when non-Jupyter source blocks are used in combination with Jupyter source blocks, e.g. when generating data files using `shell` source blocks which are subsequently processed by Jupyter source blocks.
This pull request extends `jupyter-org-execute-to-point` to consider the `:session` header argument by only evaluating Jupyter source blocks  that correspond to the same session as the source block at point or near point, …
> Session awareness in `jupyter-org-execute-to-point`

- jupyter-base.el
- jupyter-repl.el
> Set show-trailing-whitespace to nil for jupyter buffers.

- jupyter-base.el
- jupyter-client.el
- jupyter-comm-layer.el
- jupyter-ioloop.el
- jupyter-kernel-manager.el
- jupyter-messages.el
- test/jupyter-test.el
- test/test-helper.el
The previous mechanism to communicate with a kernel was too low level from the
perspective of a client. The client interfaced directly with the subprocess
abstraction, `jupyter-ioloop`, and had to handle all "events" that occurred in
the `jupyter-ioloop`, e.g. when a channel was started or stopped. But in
reality such events should not be the concern of a client.
A client should only care about events that are directly related to kernel
messages and not events related to the implementation details of *how*
communication occurs.
This commit abstracts out the way in which a client communicates with its
kernel by introducing a new `jupyter-comm-layer` class. The
`jupyter-comm-layer` class takes care of managing the communication channel
between a kernel and its clients as well as sending …
> Generalize communication with a kernel

- README.org
- jupyter-mime.el
- jupyter-org-client.el
See also: https://github.com/dzop/emacs-jupyter/pull/91
As we discussed tables are currently output inside `:RESULTS:` drawers. I haven't implemented your suggestion to add an `org-table` text property, or the special parsing needed to determine when the property should be added. I've left that for a future issue/PR -- but let me know if you prefer I take care of it now, in which case I'll look into it.
> Add pandoc conversion of rich outputs

- ob-jupyter.el
For assoc lang org-src-lang-modes may return symbol sh, (inter 'sh) will
return an error.
For some languages like C++, the corresponding language mode shall be c++
> Fix two org-src-lang-modes calc issues

- jupyter-R.el
- jupyter-client.el
- jupyter-mime.el
I'd like to have the REPL handle html outputs with `<script>` tags. I've implemented this by using `browse-url-of-buffer` to open in an external browser when the `<script>` tag is detected.
My immediate motivation was to easily inspect R dataframes with the javascript DataTables library via  R's [DT](https://rstudio.github.io/DT/) package.
> Handle `isolated` metadata property for HTML results of the R kernel

- CHANGELOG.org
- README.org
- ob-jupyter.el
In this case a new kernel is started on the remote host and the remote kernel is used. So for a `:session` like `:session /ssh:ec2:foo`, a remote kernel is started on the host `ec2` and the name of the session on that host is `foo`.
~~The issue left to be solve is how to guarantee that the ports used on the remote host are actually available.~~ See https://github.com/dzop/emacs-jupyter/issues/72#issuecomment-485622333. One option is to have the ports be configurable per host as mentioned in https://github.com/dzop/emacs-jupyter/issues/72#issuecomment-486025535, perhaps by specifying a range of ports that can be used by `emacs-jupyter` on that host.
Closes #72.
> Allow `:session` to be a remote file name for `org-mode` source blocks

- jupyter-org-client.el
Also adds handling of indentation.
Closes #114, fixes #126.
> Refactor async insertion for `org-mode` src-block results

- jupyter-org-client.el
This allows for better integration with backends that can generate org-format tables.
For example, when using `tabulate` to format pandas DataFrames as described [here](https://github.com/gregsexton/ob-ipython/blob/7147455230841744fb5b95dcbe03320313a77124/README.org#tips-and-tricks), results are inserted in a drawer, in accordance with the `text/org` mime type.
```
#+begin_src jupyter-python :session test :display org
import numpy as np
import pandas as pd
np.random.seed(123)
df = pd.DataFrame({'a': np.random.normal(1, 1, 5), 
'b': np.random.normal(5, 5, 5)})
df.rename_axis('id', inplace=True)
df
#+end_src
#+name: table1
#+results:
:RESULTS:
|   id |          a |         b |
|------+------------+-----------|
|    0 | -0.0856306 | 13.2572   |
|    1 |  1.99735   | -7.1334   |
|    2 | …
```
> jupyter-org-client.el: Add `org-table` mime type

- jupyter-org-client.el
If the `org` block outputs an image, and `org-image-actual-width` is a `list`, this PR provides customization to not to stretch the image if its width is smaller than `(car org-image-actual-width)`.
> Add jupyter-org-adjust-image-size.

- README.org
- jupyter-client.el
- jupyter-repl.el
Adds the ability to insert the results of an evaluation (by `jupyter-eval-line-or-region`) using overlays. Can be enabled by setting the customizable variable `jupyter-eval-use-overlays-p` to a non-nil value. The face used for the overlay is the `jupyter-eval-overlay` face.
> Evaluation overlays

- jupyter-client.el
Move the whitespace that was originally concatenated to the prefix variable `jupyter-eval-overlay-prefix` to the variable itself, so that it can be easily customized. For instance, in the case where one does not want any prefix, with the changes, it can be easily removed by setting the prefix variable to the empty string. Originally one would have to also modify the function `jupyter-eval-ov--propertize` to achieve the same result.
> Move whitespace to overlay prefix

- jupyter-repl.el
The described behavior for when `jupyter-repl-echo-eval-p` is `t` and the REPL buffer is not visible was not working, i.e., no pop-up buffer was being show.
> fix: show pop-up buffer when REPL not visible

- jupyter-repl.el
The previous value of this face used a dark background even on light themes, making
error messages hard to read.
This is how the proposed new setting looks like on Emacs's default theme:
> jupyter-repl-traceback face: use a light background on light themes

- jupyter-channel.el
Recently I switched to the Emacs `native-comp` branch, and while the missing require apparently didn't really hurt before, after native compiling I got an error that it couldn't find variable jupyter-channel when loading jupyter.
This seems to fix it.
> Require eieio for jupyter-channel defclass

- jupyter-repl.el
This is a fix for #219.
Looking further into the issue and with the help of the reproduction in https://github.com/nnicandro/emacs-jupyter/issues/219#issuecomment-641487092 it seems that property added to the cell text causes an infinite loop in the `font-lock-extend-region-functions` handling during fontification whenever the input is long.
> Don't add the font-lock-multiline property to finalized cell text

- Makefile
Since [this commit](https://github.com/cask/cask/commit/a8a2f72bef5e9a8ec62b6f1a0e52a8caf554570a), Cask doesn't provide `--dev` option anymore. Also, given that `dev` target looks like `init` now, I guess that the latter is not needed.
> Update `dev`, remove `init` target in Makefile (no `--dev` option)

- jupyter-comm-layer.el
- jupyter-repl.el
Having a couple of REPLs and scratch buffers opened, it's not easy to tell which scratch buffer belongs to which REPL, e.g.:
```
*jupyter-repl[kernel1]*
*jupyter-repl[kernel2]*-sess1
*jupyter-repl[kernel2]*-sess2
*jupyter-scratch[session=abe2f34b…]*
*jupyter-scratch[session=14695a88…]*
*jupyter-scratch[session=ad5c9748…]*
```
Let's say that I want to switch to a scratch buffer associated with `sess2` from some buffer other than its REPL. With the current naming scheme, it's not obvious which one is it. One may say: "but you can just switch to `sess2` REPL and then hit 'C-s' from there" - but this is a bit tedious, especially when someone wants to switch directly to some scratch buffer from the current window.
Therefore, I propose a small change which would render the previous example as …
> Make scratch buffers easier to identify

- .travis.yml
- appveyor.yml
- jupyter-org-client.el
- test/jupyter-test.el
Ensure correct output order when using Pandoc processes to convert code snippets to Org syntax. Fixes #351.
> Pandoc conversion delay and output order

- jupyter-kernelspec.el
- jupyter-repl.el
- test/jupyter-test.el
- test/test-helper.el
Fixes #371.
Turns out that there's no need to wrap `jupyter-run-repl`'s `KERNEL-NAME` in `^$`, as only `^` is needed when kernelspecs are sorted by names - and I think that this is actually closer to the original semantics, i.e. being able to specify just `python` instead of `python3` or `julia` instead of `julia-X.Y`.
With this approach, there's also no need for this extra call to `jupyter-find-kernelspecs` in `jupyter-run-repl` (and by extension, for this "fragile" check if `jupyter-run-repl` has been called interactively).
So, probably the most "controversial" change in this PR is "starting with `NAME`" instead of "matching `NAME`" in `jupyter-guess-kernelspec` - but I think that [the original idea for this fix](https://github.com/nnicandro/emacs-jupyter/issues/371#issuecomment-10385147 …
> Sort available kernelspecs; guess with ^; use guessing in jupyter-run-repl

- jupyter-tramp.el
Fixes file-not-found error when using `dired`.
> Use TRAMP handler for `access-file`

- jupyter-kernelspec.el
Would fix #301 
The PR limits the logs to `ERROR` so that the function (`jupyter-available-kernelspecs`) can still work if there is a warning. If `ERROR` or above is printed, probably it's a good idea for the function to fail?
> Fix available-kernelspecs failing from warning output

- jupyter-server.el
I got the following error on Emacs 28.2, MacOS, and fixed it:
```
Debugger entered--Lisp error: (wrong-type-argument listp #s(jupyter-kernelspec :name "python3" :plist (:argv ["python" "-m" "ipykernel_launcher" "-f" "{connection_file}"] :env nil :display_name "Python 3 (ipykernel)" :language "python" :interrupt_mode "signal" :metadata (:debugger t)) :resource-directory nil))
```
> Fix `(wrong-type-argument lisp ...)`

- jupyter-org-client.el
Do add an extra space when inserting an example block and an image.
Applies to situations like these:
Without this, inserting results will eat up lines.
> correct spacing for example + image

- README.org
- jupyter-org-client.el
This is a minor change which allows resolving the filename extension from the MIME type even if `:file` has been specified (and no specific extension was specified in `:file`).
This can be very useful when the MIME type of the output can change between evaluations but one still wants to use filenames other than the automatically generated one from `jupyter-org-image-file-name`.
One pain-point I repeatedly run is that I want to specify `:file`, but the file-extension used is not something I know ahead of time, e.g. if I'm plotting something in Julia, the resulting MIME type will be `png` if I've run `pyplot()` in some previous src-block, while it will be `svg` if I've run `gr()` in a previous src-block. Then it's useful for me to just specify the "base-name", say, `:file image/output` and …
> Allow resolution of file extension when :file is specified

- jupyter-org-client.el
Upstream org commit f01390c changed the behavior of org-inside-LaTeX-fragment-p which now checks for both latex fragments and environments
> Fix jupyter-org--parse-latex-element

- jupyter.el
Trying to use the elpaca package manager currently gives bytecomp errors of "Error: Org version mismatch." when trying to use a non-builtin org version. The elpaca dependency manager doesn't load the newer version of org in the bytecomp process since it isn't declared in the Package-Requires section.
I wasn't totally sure what minimum org version to specify, so I went with the org version that shipped with emacs 26.
> Add org to Package-Requires

- jupyter-env.el
This PR makes the `jupyter` executable configurable.
My use case is setting it to a project-local executable built by Bazel, instead of having a pip-installed executable available in the `$PATH`.
> Make the jupyter executable configurable

- jupyter-org-client.el
Upstream org commit 4fcdcb4 changed the behavior of `org-element-context` which now uses `org-element-deferred-create` which is incompatible with inserting elements created from with-temp-buffer outside its scope.
Note that the first error I ran into which led to this PR was actually
```
Jupyter: I/O subscriber error: (error "‘org-element-at-point’ cannot be used in non-Org buffer #<buffer  *temp*> (fundamental-mode)")
```
which at first I thought was related to #492 which is due to upstream org commit f135954, however I realized that that issued seemed to be fixed in master already and simply adding a call to `(org-mode)` in `jupyter-org--parse-latex-element` fixed that error but exposed this deeper one which I had missed since I upgraded from a commit prior to 4fcdcb4 past commit …
> Fix jupyter-org--parse-latex-element again

- jupyter-repl.el
This PR makes the `jupyter-completion-at-point` hook DEPTH in `completion-at-point-functions` configurable. This is useful, for example, if one wants to give lower priority to `jupyter-completion-at-point` so that other completion at point functions like `lsp-completion-at-point` can run.
> Make `jupyter-completion-at-point` hook DEPTH configurable

- ob-jupyter.el
Ensuring this function is called after `jupyter-org-interaction-mode` in `org-mode-hook` to ensure correct fontification of errors (i.e. handling ansi-color escape characters).
> ob-jupyter.el: Delay `org-babel-jupyter-make-local-aliases` hook.

- jupyter-repl.el
If raw is nil then with SageMath kernels the history we're getting is `Integer(1) + Integer(2)` if `1+2` was issued as a command before, i.e. SageMath does some heavy processing of inputs.
> request raw history

- jupyter-server-kernel.el
I was trying out emacs-jupyter to connect to [Paperspace Gradient](https://www.paperspace.com) using their token authenticated [remote kernel](https://docs.digitalocean.com/products/paperspace/notebooks/how-to/connect-remote-kernel/). I noticed that some code executions didn't output anything (e.g. `.describe()`). 
It turns out that the current `:on-message` handler doesn't properly handle partial messages. If `websocket-frame-completep` returns `nil` we should wait for the next frame and accumulate the message.
We also add `continuation` `websocket-frame-opcode` as a valid string response. I'm not sure what impact this will have since `continuation` isn't actually a type like `text` or `binary`
For those interested in connecting to Paperspace Gradient; you have to connect WITHOUT using a …
> Read websocket frame until completed

- jupyter-env.el
Sometimes control characters appear in the connection file name, this is a trivial fix to modify the regular expression to avoid this. One could also improve the expression to pick out the JSON filetype probably, but I wanted to keep the change minor.
> Fix control characters appearing in connection file.
